### ISSUE TITLE
필독!! 

### ISSUE THREAD

**Issue by jaesung-eee** [sejongsmarcle/2023_Spring_SMARCLE-Saenaegi_Study#1]
# 0주차 미션!!
> 3/19 ~ 3/29 까지
- 깃허브 계정 만들기
- readme 작성법 익히기
- 각 팀에 해당하는 경로에 간단한 자기소개 글을 이름.md 로 작성(멘토,멘티) 하기
 
## 주의 

- 깃허브 계정을 만드면 우선 이 이슈에 **가입할때 사용한 이메일을 꼭 남겨주세요!!** 업로드 권한을 드릴 때 필요합니다!!

- readme.md 파일은 `2023_Spring_SMARCLE-Saenaegi_Study/스터디 자료/0주차/n팀/이름.md` 로 폴더를 맞춰서 업로드 해주세요.
- 앞으로 결과물을 올리게 될 경로는  `2023_Spring_SMARCLE-Saenaegi_Study/스터디 자료/0주차/n팀` 입니다!!

## 필독 

**깃허브 계정을 만드시면 가입한 이메일 주소를 꼭 이곳에 코멘트 남겨주세요**

**업로드 권한을 드릴때 필요합니다. 이메일로 초대장이 가면 꼭 수락 해주세요!!**

**깃허브 업로드는 멘티만!!(2학년 멘토는 멘티와 같은 파일에 작성해도 괜찮음)**

**이 방식으로 이번 프로그램을 진행할 예정입니다 꼭 익숙해지세요!!** 

## 참고자료 

- [마크다운작성법 글](https://gist.github.com/ihoneymon/652be052a0727ad59601)
- [마크다운작성법 영상](https://www.youtube.com/watch?v=kMEb_BzyUqk)

**Comment by catuscio** [comment]
최규민
catuscio@hotmail.com

**Comment by wjdwotjr0318** [comment]
정재석
wjdwotjr0318@gmail.com

**Comment by shihyunlim** [comment]
임시현
shihyunlim1217@naver.com

**Comment by Kang-seonguk** [comment]
jk1014496@gmail.com

**Comment by Kang-seonguk** [comment]
강성욱
jk1014496@gmail.com

**Comment by kj0409** [comment]
박경준
newmeka12@gmail.com

**Comment by yoonie03** [comment]
yoonie348@gmail.com
조윤정

**Comment by Jiyoung0219** [comment]
wldud040219@naver.com
강지영

**Comment by Gyemoo** [comment]
이계무
lgm528@naver.com

**Comment by kwohyo** [comment]
권효정
kwhj1106@naver.com

**Comment by parkgwangsuk** [comment]
박광석
pks266426@gmail.com

**Comment by KMS-04** [comment]
김민성
wdson71602@naver.com

**Comment by Minnjeongg** [comment]
석민정
alwjd040422@naver.com

**Comment by Shinyoung-P** [comment]
박신영
sypzang@gmail.com

**Comment by dhtmdals** [comment]
오승민
smoh01@naver.com

**Comment by liye82484** [comment]
조예림
liye82484@gmail.com

**Comment by chamxmi** [comment]
황찬미
chamm6012@naver.com

**Comment by Kim-Beom-Yeol** [comment]
bybyby7348@naver.com

**Comment by Kim-Beom-Yeol** [comment]
김범열
bybyby7348@naver.com

**Comment by tkddhks03** [comment]
김상완
tkddhks03@gmail.com

**Comment by qwerie** [comment]
전유진
qwerie8899@gmail.com

**Comment by eun-kyeol** [comment]
한은결
silverwavvee@gmail.com

**Comment by cheonwon0430** [comment]
천승원
1000swsw@gmail.com

**Comment by kimhayunn** [comment]
dbs8654@naver.com

**Comment by chaneol** [comment]
박찬얼
bloompce@gmail.com

**Comment by kimhayunn** [comment]
김하윤
dbs8654@naver.com

**Comment by ZSTEP-SMARCLE** [comment]
김태경
zstep2014@naver.com
